#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo '\n\033[1;92mSimulação - malha 01.\033[0m\n'
cd caso
./Allrun
cd ..

cd plotUx
gnuplot *.plt
cd ..

cd plotUy
gnuplot *.plt
cd ..

